### ISSUE TITLE
Pinterest media tag

### ISSUE THREAD

**Issue by GeeTee** [pchynoweth/svelte-share-buttons-component#158]
Thank you for your work,
every thing is perfect but
I cant get media tag working, with a cloudinary url.
sveltekit  : "^1.20.4"
svelte-share-buttons-component : "^2.0.0"

media ulr looks : https://res.cloudinary.com/<cloud_name>/image/upload/c_scale,w_200,f_jpg/<public_id>
That url is working in browser.

An advice please

**Comment by pchynoweth** [comment]
It's difficult to say for certain without a working URL to experiment with.  I would guess pinterest isn't recognising the URL as an image URL, or doesn't have access to the image.
