### ISSUE TITLE
LinkedIn Button 

### ISSUE THREAD

**Issue by sanderjson** [pchynoweth/svelte-share-buttons-component#2]
The LinkedIn button is not working as intended - the description is not in the post. From the demo site it appears to work but the copy is not the same. Is LinkedIn just generating the content from the meta tags?

**Comment by pchynoweth** [comment]
Thanks @sanderjson.  You are right.  It looks like Microsoft stopped processing most of the parameters in April 2020: https://stackoverflow.com/a/61583006/1390927.  They now parse the information from meta tags and if none are present from the content instead.

I'll update the LinkedIn button accordingly.
