### ISSUE TITLE
Pinterest button broken

### ISSUE THREAD

**Issue by darajava** [pchynoweth/svelte-share-buttons-component#9]
Thanks for the great package! Saved me lots of time and the buttons look great!

The pinterest button is broken with current params though. It seems to expect an image? Not really sure. You can take a look at an example here: https://whatawasteofsixeuro.com . I supplied `url` and `title` as described in the README.

**Comment by pchynoweth** [comment]
Thank you.  I can't take credit for the design of the buttons themselves.  They are all from here: https://github.com/mxstbr/sharingbuttons.io.

I think I understand the problem.  Pinterest expect you to provide an image url.  I'll see what I can do at the weekend.
